# Generated by Django 2.2.17 on 2021-02-01 16:24

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HmrcMail",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("replied", "Replied"),
                            ("retry", "Retry"),
                            ("failed", "Failed"),
                        ],
                        default="accepted",
                    ),
                ),
                (
                    "extract_type",
                    models.TextField(
                        choices=[
                            ("usage_update", "Usage update"),
                            ("usage_reply", "Usage Reply"),
                            ("licence_update", "Licence Update"),
                            ("licence_reply", "Licence Reply"),
                            ("licence_data", "Licence Data"),
                        ],
                        null=True,
                    ),
                ),
                ("source", models.TextField()),
                ("source_run_number", models.IntegerField()),
                ("edi_filename", models.TextField()),
                ("edi_data", models.TextField()),
                ("licence_ids", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="RetrievedMail",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("message_id", models.TextField()),
                ("sender", models.TextField()),
                ("status", models.TextField(choices=[("valid", "Valid"), ("invalid", "Invalid")], default="invalid")),
            ],
        ),
    ]
