# Generated by Django 2.2.18 on 2021-05-05 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mock_hmrc", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hmrcmail",
            name="extract_type",
            field=models.TextField(
                choices=[
                    ("usage_data", "Usage Data"),
                    ("usage_reply", "Usage Reply"),
                    ("licence_reply", "Licence Reply"),
                    ("licence_data", "Licence Data"),
                ],
                null=True,
            ),
        ),
    ]
