version: '3'

services:
  lite-hmrc-postgres:
    container_name: "lite-hmrc-postgres"
    environment:
      - LITEHMRC_DB_USER=postgres
      - LITEHMRC_DB_PASSWORD=password
      - LITEHMRC_DB_SCHEMA=postgres
      - POSTGRES_PASSWORD=password
    build: './database'
    expose:
      - 5432
    ports:
      - 5432:5432

  lite-hmrc-intg:
    container_name: "lite-hmrc-intg"
    build:
      context: .
      dockerfile: ./circleci.Dockerfile
    env_file:
      - local.env
    environment:
      - DATABASE_URL=postgres://postgres:password@lite-hmrc-postgres:5432/postgres
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - lite-hmrc-postgres
    expose:
      - 8000
    entrypoint: dockerize -wait tcp://lite-hmrc-postgres:5432 -timeout 300s
    command: ./background_tasks_up.sh

  check-background-tasks:
    image: jwilder/dockerize
    entrypoint: dockerize -wait file:///app/.background-tasks-is-ready -timeout 300s
    env_file:
      - local.env
    environment:
      - DATABASE_URL=postgres://postgres:password@lite-hmrc-postgres:5432/postgres
    volumes:
      - .:/app
    command: |
      true
    depends_on:
      - lite-hmrc-intg
