version: "3.8"

services:
    lite-hmrc-intg:
      networks:
        - backend
        - icms_public

    celery-worker:
        networks:
          - backend
          - icms_public

    redis:
      networks:
        - backend

    celery-beat:
        networks:
          - backend

    celery-flower:
        networks:
          - backend

    mailhog:
        networks:
          - backend

    lite-hmrc-postgres:
        networks:
          - backend

networks:
  backend:
  icms_public:
    name: "icms_public"
