version: "3.8"

services:
    redis:
        networks:
          - backend

    celery-worker:
        networks:
          - backend

    celery-beat:
        networks:
          - backend

    mailhog:
        networks:
          - backend

    lite-hmrc-postgres:
        networks:
          - backend

    lite-hmrc-intg:
        networks:
          - backend
          - icms_backend

networks:
  backend:
  icms_backend:
    name: "icms_backend"
