# Generated by Django 4.1.10 on 2023-08-04 08:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "extract_type",
                    models.CharField(
                        choices=[
                            ("usage_data", "Usage Data"),
                            ("usage_reply", "Usage Reply"),
                            ("licence_reply", "Licence Reply"),
                            ("licence_data", "Licence Data"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("reply_pending", "Reply Pending"),
                            ("reply_received", "Reply Received"),
                            ("reply_sent", "Reply Sent"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("edi_filename", models.TextField(blank=True, null=True)),
                ("edi_data", models.TextField(blank=True, null=True)),
                ("sent_filename", models.TextField(blank=True, null=True)),
                ("sent_data", models.TextField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("response_filename", models.TextField(blank=True, null=True)),
                ("response_data", models.TextField(blank=True, null=True)),
                ("response_date", models.DateTimeField(blank=True, null=True)),
                ("response_subject", models.TextField(blank=True, null=True)),
                ("sent_response_filename", models.TextField(blank=True, null=True)),
                ("sent_response_data", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "mail",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="LicencePayload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("insert", "Insert"),
                            ("cancel", "Cancel"),
                            ("replace", "Replace"),
                        ],
                        max_length=7,
                    ),
                ),
                ("icms_id", models.UUIDField()),
                ("reference", models.CharField(max_length=35)),
                ("data", models.JSONField(default=dict)),
                ("received_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("is_processed", models.BooleanField(default=False)),
                ("skip_process", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["received_at"],
                "unique_together": {("icms_id", "action")},
            },
        ),
        migrations.CreateModel(
            name="LicenceData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("licence_ids", models.TextField()),
                ("hmrc_run_number", models.IntegerField()),
                ("source_run_number", models.IntegerField(null=True)),
                (
                    "source",
                    models.CharField(choices=[("HMRC", "HMRC"), ("ICMS", "ICMS")], max_length=10),
                ),
                (
                    "licence_payloads",
                    models.ManyToManyField(
                        help_text="LicencePayload records linked to this LicenceData instance",
                        related_name="+",
                        to="mail.licencepayload",
                    ),
                ),
                (
                    "mail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="mail.mail"
                    ),
                ),
            ],
            options={
                "ordering": ["mail__created_at"],
            },
        ),
    ]
