# Generated by Django 2.2.17 on 2021-01-29 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mail",
            name="extract_type",
            field=models.CharField(
                choices=[
                    ("usage_update", "Usage update"),
                    ("usage_reply", "Usage Reply"),
                    ("licence_update", "Licence Update"),
                    ("licence_reply", "Licence Reply"),
                    ("licence_data", "Licence Data"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="LicenceData",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("licence_ids", models.TextField()),
                ("hmrc_run_number", models.IntegerField()),
                ("source_run_number", models.IntegerField(null=True)),
                (
                    "source",
                    models.CharField(choices=[("SPIRE", "SPIRE"), ("LITE", "LITE"), ("HMRC", "HMRC")], max_length=10),
                ),
                ("mail", models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to="mail.Mail")),
            ],
            options={
                "ordering": ["mail__created_at"],
            },
        ),
    ]
