# Generated by Django 2.2.17 on 2021-02-03 19:20

import uuid

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0002_auto_20210129_0232"),
    ]

    operations = [
        migrations.CreateModel(
            name="MailboxConfig",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "username",
                    models.TextField(help_text="Username of the POP3 mailbox", primary_key=True, serialize=False),
                ),
                (
                    "start_message_id",
                    models.TextField(
                        default=None,
                        help_text="Process messages from this message ID onwards, can be Null if messages should be processed from the very first message in the mailbox",
                        null=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MailReadStatus",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("message_id", models.TextField()),
                ("status", models.TextField(choices=[("READ", "Read"), ("UNREAD", "Unread")], default="UNREAD")),
                ("mailbox", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="mail.MailboxConfig")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
