# Generated by Django 2.2.8 on 2020-01-27 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0002_auto_20200122_1507"),
    ]

    operations = [
        migrations.AddField(
            model_name="licenceusage",
            name="hmrc_run_number",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="licenceusage",
            name="spire_run_number",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="mail",
            name="extract_type",
            field=models.CharField(
                choices=[
                    ("usage_update", "Usage update"),
                    ("usage_reply", "Usage Reply"),
                    ("licence_update", "Licence Update"),
                    ("licence_reply", "Licence Reply"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="mail",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("reply_pending", "Reply Pending"),
                    ("reply_sent", "Reply Sent"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
