# Generated by Django 2.2.19 on 2021-03-05 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0005_auto_20210204_1019"),
    ]

    operations = [
        migrations.DeleteModel(name="LicenceUpdate",),
    ]
