# Generated by Django 2.2.8 on 2020-01-28 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0006_auto_20200127_1608"),
    ]

    operations = [
        migrations.AlterModelTable(name="mail", table="mail",),
    ]
