# Generated by Django 2.2.9 on 2020-02-14 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0007_auto_20200128_1545"),
    ]

    operations = [
        migrations.AddField(
            model_name="mail",
            name="response_subject",
            field=models.TextField(blank=True, null=True),
        ),
    ]
