# Generated by Django 2.2.18 on 2021-05-05 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0007_auto_20210308_1103"),
    ]

    operations = [
        migrations.RenameModel(old_name="UsageUpdate", new_name="UsageData",),
        migrations.RenameField(model_name="transactionmapping", old_name="usage_update", new_name="usage_data",),
        migrations.AlterField(
            model_name="mail",
            name="extract_type",
            field=models.CharField(
                choices=[
                    ("usage_data", "Usage Data"),
                    ("usage_reply", "Usage Reply"),
                    ("licence_reply", "Licence Reply"),
                    ("licence_data", "Licence Data"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="transactionmapping", unique_together={("licence_reference", "line_number", "usage_data")},
        ),
    ]
