# Generated by Django 2.2.18 on 2021-05-08 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0008_auto_20210505_1513"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mailboxconfig",
            name="start_message_id",
        ),
        migrations.RemoveField(
            model_name="mailreadstatus",
            name="message_id",
        ),
        migrations.AddField(
            model_name="mailreadstatus",
            name="message_num",
            field=models.TextField(
                default="",
                help_text="Sequence number of the message as assigned by pop3 when the messages list is requested from the mailbox",
            ),
        ),
    ]
