# Generated by Django 2.2.18 on 2021-05-08 23:30

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0009_auto_20210508_2322"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailreadstatus",
            name="message_id",
            field=models.UUIDField(
                default=uuid.uuid4,
                help_text="Unique Message-ID of the message that is retrieved from the message header",
            ),
        ),
    ]
