# Generated by Django 2.2.18 on 2021-05-19 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0010_mailreadstatus_message_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailreadstatus",
            name="message_id",
            field=models.TextField(
                default="", help_text="Unique Message-ID of the message that is retrieved from the message header"
            ),
        ),
    ]
