# Generated by Django 2.2.18 on 2021-05-19 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0011_auto_20210519_0859"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailreadstatus",
            name="message_id",
            field=models.TextField(
                default="<function uuid4 at 0x7f6306961a60>",
                help_text="Unique Message-ID of the message that is retrieved from the message header",
                unique=True,
            ),
        ),
    ]
