# Generated by Django 2.2.23 on 2021-07-29 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0013_auto_20210702_1501"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="transactionmapping",
            unique_together=set(),
        ),
    ]
