# Generated by Django 2.2.24 on 2022-01-20 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0014_auto_20210729_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='licencepayload',
            name='skip',
            field=models.BooleanField(default=False),
        ),
    ]
