# Generated by Django 3.2.16 on 2022-11-09 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0019_alter_licencepayload_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='licencedata',
            name='licence_payloads',
            field=models.ManyToManyField(help_text='LicencePayload records linked to this LicenceData instance', related_name='_mail_licencedata_licence_payloads_+', to='mail.LicencePayload'),
        ),
    ]
