# Generated by Django 3.2.16 on 2022-12-28 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0020_licencedata_licence_payloads"),
    ]

    operations = [
        migrations.AddField(
            model_name="licencepayload",
            name="skip_process",
            field=models.BooleanField(default=False),
        ),
    ]
