# Generated by Django 3.2.16 on 2023-01-06 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0021_licencepayload_skip_process'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licencedata',
            name='source',
            field=models.CharField(choices=[('HMRC', 'HMRC'), ('ICMS', 'ICMS')], max_length=10),
        ),
    ]
