# Generated by Django 3.2.16 on 2023-01-06 15:48

from django.db import migrations, models


class Migration(migrations.Migration):
    """Remove old models.

    Summary:
        - Delete model GoodIdMapping
        - Delete model LicenceIdMapping
        - Remove field mailbox from mailreadstatus
        - Delete model OrganisationIdMapping
        - Remove field usage_data from transactionmapping
        - Remove field mail from usagedata
        - Remove field old_lite_id from licencepayload
        - Remove field old_reference from licencepayload
        - Alter field id on licencedata
        - Alter field action on licencepayload
        - Delete model MailboxConfig
        - Delete model MailReadStatus
        - Delete model TransactionMapping
        - Delete model UsageData
    """


    dependencies = [
        ('mail', '0022_alter_licencedata_source'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GoodIdMapping',
        ),
        migrations.DeleteModel(
            name='LicenceIdMapping',
        ),
        migrations.RemoveField(
            model_name='mailreadstatus',
            name='mailbox',
        ),
        migrations.DeleteModel(
            name='OrganisationIdMapping',
        ),
        migrations.RemoveField(
            model_name='transactionmapping',
            name='usage_data',
        ),
        migrations.RemoveField(
            model_name='usagedata',
            name='mail',
        ),
        migrations.RemoveField(
            model_name='licencepayload',
            name='old_lite_id',
        ),
        migrations.RemoveField(
            model_name='licencepayload',
            name='old_reference',
        ),
        migrations.AlterField(
            model_name='licencedata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='licencepayload',
            name='action',
            field=models.CharField(choices=[('insert', 'Insert'), ('cancel', 'Cancel'), ('replace', 'Replace')], max_length=7),
        ),
        migrations.DeleteModel(
            name='MailboxConfig',
        ),
        migrations.DeleteModel(
            name='MailReadStatus',
        ),
        migrations.DeleteModel(
            name='TransactionMapping',
        ),
        migrations.DeleteModel(
            name='UsageData',
        ),
    ]
